// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarGuinchos.Data;

#nullable disable

namespace StarGuinchos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StarGuinchos.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutorizadoPublicacao")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("StarGuinchos.Models.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_solicitacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destino")
                        .HasColumnType("longtext");

                    b.Property<double?>("DestinoLat")
                        .HasColumnType("double");

                    b.Property<double?>("DestinoLng")
                        .HasColumnType("double");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<double?>("PontoPartidaLat")
                        .HasColumnType("double");

                    b.Property<double?>("PontoPartidaLng")
                        .HasColumnType("double");

                    b.Property<string>("Ponto_partida")
                        .HasColumnType("longtext");

                    b.Property<string>("Problema")
                        .HasColumnType("longtext");

                    b.Property<string>("Status_solicitacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Veiculo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Solicitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
